#ifndef ASTNODEOP_H
#define ASTNODEOP_H

typedef enum {
    A_ADD=1, A_SUBTRACT, A_MULTIPLY, A_DIVIDE,
    A_EQUAL, A_NOTEQUAL, A_LESSTHAN, A_GREATERTHAN, A_LESSEQUAL, A_GREATEREQUAL,
    A_INTLIT,
    A_IDENT, A_LVIDENT, A_ASSIGN
} ASTNodeOp;

#endif